// =============================================================================
// SAMPLE TEST PROFILES
// =============================================================================

import type { StudentProfile } from "./types";

export const SAMPLE_PROFILES: { name: string; profile: StudentProfile }[] = [
  {
    name: "STEM-Focused Student",
    profile: {
      grade: 11,
      interests_free_text: "I love coding, building robots, and participating in hackathons. I enjoy learning Python and JavaScript.",
      interests_by_category: {
        academic: true,
        creative: false,
        social: false,
        technical: true,
        sports: false,
        music: false,
        business: false,
        health_wellness: false,
        other: false,
      },
      goals_selected: ["coding", "stem", "college"],
      goals_free_text: "I want to become a software engineer and work at a tech company.",
      time_availability_hours_per_week: 10,
      learning_preferences: ["handson", "video"],
      past_activities: "I built a weather app using Python and APIs. I also led my school's robotics club and helped debug code for our competition robot.",
      past_achievements: "Won 2nd place at regional hackathon. Got state award for robotics.",
      challenges: "I struggle with communicating technical concepts to non-technical people. I also need to improve my time management when working on multiple projects.",
      skills: {
        problemSolving: 4,
        communication: 2,
        technicalSkills: 4,
        creativity: 3,
        leadership: 3,
        selfManagement: 2,
      },
    },
  },
  {
    name: "Leadership-Focused Student",
    profile: {
      grade: 12,
      interests_free_text: "Public speaking, debate team, student government, and community service.",
      interests_by_category: {
        academic: true,
        creative: false,
        social: true,
        technical: false,
        sports: false,
        music: false,
        business: true,
        health_wellness: false,
        other: false,
      },
      goals_selected: ["leadership", "publicSpeaking", "networking"],
      goals_free_text: "I want to run for student body president and eventually pursue a career in politics or business.",
      time_availability_hours_per_week: 8,
      learning_preferences: ["group", "mentor"],
      past_activities: "I organized a charity fundraiser that raised $5000. I mentored younger students in debate club and led weekly practice sessions.",
      past_achievements: "Won best speaker at state debate competition. Elected class representative for 3 years.",
      challenges: "I sometimes take on too many responsibilities at once. I need to work on delegating tasks to others and saying no when I'm overwhelmed.",
      skills: {
        problemSolving: 3,
        communication: 5,
        technicalSkills: 1,
        creativity: 2,
        leadership: 5,
        selfManagement: 3,
      },
    },
  },
  {
    name: "Creative Student",
    profile: {
      grade: 10,
      interests_free_text: "Art, music production, graphic design, and creative writing.",
      interests_by_category: {
        academic: false,
        creative: true,
        social: false,
        technical: false,
        sports: false,
        music: true,
        business: false,
        health_wellness: false,
        other: false,
      },
      goals_selected: ["creativity", "writing"],
      goals_free_text: "I want to become a professional artist or work in the creative industry.",
      time_availability_hours_per_week: 6,
      learning_preferences: ["handson", "video"],
      past_activities: "I designed the school yearbook cover and created promotional posters for school events. I also compose music in my free time.",
      past_achievements: "Won the school art competition. My short story was published in the school magazine.",
      challenges: "I have trouble finishing projects once the initial excitement wears off. I also struggle with promoting my own work and putting myself out there.",
      skills: {
        problemSolving: 2,
        communication: 3,
        technicalSkills: 2,
        creativity: 5,
        leadership: 1,
        selfManagement: 2,
      },
    },
  },
  {
    name: "Minimal Evidence Student",
    profile: {
      grade: 9,
      interests_free_text: "I like playing video games and hanging out with friends.",
      interests_by_category: {
        academic: false,
        creative: false,
        social: true,
        technical: false,
        sports: false,
        music: false,
        business: false,
        health_wellness: false,
        other: true,
      },
      goals_selected: [],
      goals_free_text: "",
      time_availability_hours_per_week: 2,
      learning_preferences: ["video"],
      past_activities: "I sometimes help my friends with homework.",
      past_achievements: "",
      challenges: "I'm not sure what I want to do yet. I find it hard to stay motivated for schoolwork.",
      skills: {
        problemSolving: 1,
        communication: 2,
        technicalSkills: 1,
        creativity: 1,
        leadership: 0,
        selfManagement: 1,
      },
    },
  },
  {
    name: "Athlete & Sports Leader",
    profile: {
      grade: 11,
      interests_free_text: "Basketball, track and field, fitness training, and sports psychology. I'm interested in how athletes train mentally and physically.",
      interests_by_category: {
        academic: false,
        creative: false,
        social: true,
        technical: false,
        sports: true,
        music: false,
        business: false,
        health_wellness: true,
        other: false,
      },
      goals_selected: ["leadership", "career", "college"],
      goals_free_text: "I want to get a basketball scholarship and eventually become a sports coach or physical therapist.",
      time_availability_hours_per_week: 6,
      learning_preferences: ["handson", "video", "mentor"],
      past_activities: "I'm the captain of the varsity basketball team. I organized summer training camps for younger players. I also volunteer at the community gym teaching basic fitness.",
      past_achievements: "Team MVP for 2 consecutive years. Led the team to regional championships. Certified in basic first aid and CPR.",
      challenges: "Balancing academics with sports practice is tough. I also get nervous during high-pressure games and need to work on mental toughness.",
      skills: {
        problemSolving: 3,
        communication: 4,
        technicalSkills: 1,
        creativity: 2,
        leadership: 5,
        selfManagement: 4,
      },
    },
  },
  {
    name: "Entrepreneur & Business Mind",
    profile: {
      grade: 12,
      interests_free_text: "Starting businesses, marketing, social media management, and financial literacy. I run a small reselling business online.",
      interests_by_category: {
        academic: false,
        creative: true,
        social: true,
        technical: true,
        sports: false,
        music: false,
        business: true,
        health_wellness: false,
        other: false,
      },
      goals_selected: ["entrepreneurship", "networking", "leadership"],
      goals_free_text: "I want to start my own company before graduating college. Interested in e-commerce and digital marketing.",
      time_availability_hours_per_week: 12,
      learning_preferences: ["handson", "mentor", "reading"],
      past_activities: "Started a sneaker reselling business that made $3000 in profit. Managed social media for a local small business. Created a business club at school and organized guest speaker events.",
      past_achievements: "Won the school's young entrepreneur competition. Featured in local newspaper for my business. Grew Instagram account to 5000 followers for a client.",
      challenges: "I struggle with long-term planning and sometimes get distracted by new business ideas. I also need to improve my accounting and financial management skills.",
      skills: {
        problemSolving: 4,
        communication: 4,
        technicalSkills: 3,
        creativity: 4,
        leadership: 4,
        selfManagement: 3,
      },
    },
  },
  {
    name: "Science Researcher",
    profile: {
      grade: 11,
      interests_free_text: "Biology, chemistry, environmental science, and scientific research. I love conducting experiments and analyzing data.",
      interests_by_category: {
        academic: true,
        creative: false,
        social: false,
        technical: true,
        sports: false,
        music: false,
        business: false,
        health_wellness: true,
        other: false,
      },
      goals_selected: ["stem", "college", "career"],
      goals_free_text: "I want to become a research scientist, possibly in biotechnology or environmental science. PhD is my long-term goal.",
      time_availability_hours_per_week: 10,
      learning_preferences: ["reading", "handson", "mentor"],
      past_activities: "Conducted an independent research project on water quality in local streams. Participated in a summer research internship at a university lab. Member of Science Olympiad team focusing on biology events.",
      past_achievements: "Won 1st place in regional science fair. Published research summary in student science journal. Gold medal in Science Olympiad state competition.",
      challenges: "I tend to get too focused on details and lose sight of the bigger picture. I also find it hard to explain complex scientific concepts to people without a science background.",
      skills: {
        problemSolving: 5,
        communication: 2,
        technicalSkills: 4,
        creativity: 3,
        leadership: 2,
        selfManagement: 4,
      },
    },
  },
  {
    name: "Performing Arts Student",
    profile: {
      grade: 10,
      interests_free_text: "Theater, acting, singing, and dance. I love performing on stage and expressing emotions through art.",
      interests_by_category: {
        academic: false,
        creative: true,
        social: true,
        technical: false,
        sports: false,
        music: true,
        business: false,
        health_wellness: false,
        other: false,
      },
      goals_selected: ["creativity", "publicSpeaking", "networking"],
      goals_free_text: "I want to pursue performing arts in college and eventually work on Broadway or in film.",
      time_availability_hours_per_week: 8,
      learning_preferences: ["handson", "group", "mentor"],
      past_activities: "Lead roles in 3 school musicals. Took voice lessons for 5 years. Choreographed a dance routine for the school talent show. Participated in community theater productions.",
      past_achievements: "Best Actor award at regional theater festival. Selected for all-state choir. My dance performance went viral on TikTok with 100k views.",
      challenges: "I deal with stage fright before big performances. I also struggle with rejection after auditions and need to build more resilience.",
      skills: {
        problemSolving: 2,
        communication: 5,
        technicalSkills: 1,
        creativity: 5,
        leadership: 3,
        selfManagement: 3,
      },
    },
  },
  {
    name: "Healthcare Aspirant",
    profile: {
      grade: 12,
      interests_free_text: "Medicine, healthcare, volunteering at hospitals, and helping people. I'm fascinated by how the human body works.",
      interests_by_category: {
        academic: true,
        creative: false,
        social: true,
        technical: false,
        sports: false,
        music: false,
        business: false,
        health_wellness: true,
        other: false,
      },
      goals_selected: ["career", "college", "leadership"],
      goals_free_text: "I want to become a doctor, specifically a pediatrician or surgeon. Pre-med track in college is my plan.",
      time_availability_hours_per_week: 7,
      learning_preferences: ["reading", "handson", "mentor"],
      past_activities: "Volunteered 200+ hours at local hospital. Shadowed doctors in ER and pediatrics. Led the health awareness club and organized blood drives. Certified EMT.",
      past_achievements: "Received hospital volunteer of the year award. CPR and EMT certifications. 4.0 GPA in all science courses.",
      challenges: "I struggle with maintaining work-life balance while preparing for medical school. I also find it emotionally difficult when patients have bad outcomes.",
      skills: {
        problemSolving: 4,
        communication: 4,
        technicalSkills: 3,
        creativity: 2,
        leadership: 4,
        selfManagement: 4,
      },
    },
  },
  {
    name: "Gaming & Esports Enthusiast",
    profile: {
      grade: 10,
      interests_free_text: "Competitive gaming, game streaming, esports strategy, and game design. I spend hours analyzing game mechanics and improving my skills.",
      interests_by_category: {
        academic: false,
        creative: true,
        social: true,
        technical: true,
        sports: false,
        music: false,
        business: false,
        health_wellness: false,
        other: true,
      },
      goals_selected: ["coding", "creativity", "networking"],
      goals_free_text: "I want to either become a professional esports player or work in the gaming industry as a game designer or developer.",
      time_availability_hours_per_week: 15,
      learning_preferences: ["video", "handson", "group"],
      past_activities: "Rank top 500 in Valorant. Started a Twitch stream with 200 followers. Captain of school esports team. Learning Unity game development in free time. Organized school gaming tournaments.",
      past_achievements: "Won regional esports tournament. Reached Diamond rank in multiple competitive games. Built a small game prototype in Unity.",
      challenges: "I sometimes game too much and neglect homework. I also need to work on not getting tilted when I lose and managing my competitive frustration.",
      skills: {
        problemSolving: 4,
        communication: 3,
        technicalSkills: 3,
        creativity: 3,
        leadership: 3,
        selfManagement: 2,
      },
    },
  },
  {
    name: "Environmental Activist",
    profile: {
      grade: 11,
      interests_free_text: "Climate change, sustainability, environmental policy, and outdoor activities. I'm passionate about protecting our planet.",
      interests_by_category: {
        academic: true,
        creative: false,
        social: true,
        technical: false,
        sports: false,
        music: false,
        business: false,
        health_wellness: true,
        other: true,
      },
      goals_selected: ["leadership", "career", "networking"],
      goals_free_text: "I want to work in environmental policy or become a climate scientist. Making a real impact on climate change is my mission.",
      time_availability_hours_per_week: 9,
      learning_preferences: ["reading", "group", "handson"],
      past_activities: "Founded the school's environmental club. Organized a school-wide recycling program that diverted 500 lbs of waste. Led a community tree planting initiative. Attended climate march in Washington DC.",
      past_achievements: "Recognized by city council for environmental leadership. Club grew from 5 to 50 members. Secured grant funding for school garden project.",
      challenges: "I sometimes feel overwhelmed by the scale of environmental problems. I also need to learn to work better with people who don't share my urgency about climate issues.",
      skills: {
        problemSolving: 4,
        communication: 4,
        technicalSkills: 2,
        creativity: 3,
        leadership: 5,
        selfManagement: 4,
      },
    },
  },
  {
    name: "Music Producer & DJ",
    profile: {
      grade: 11,
      interests_free_text: "Music production, DJing, sound engineering, and beat making. I use Ableton and FL Studio to create electronic music.",
      interests_by_category: {
        academic: false,
        creative: true,
        social: true,
        technical: true,
        sports: false,
        music: true,
        business: true,
        health_wellness: false,
        other: false,
      },
      goals_selected: ["creativity", "entrepreneurship", "networking"],
      goals_free_text: "I want to become a professional music producer or audio engineer. Dream of producing for major artists or scoring films.",
      time_availability_hours_per_week: 12,
      learning_preferences: ["video", "handson", "mentor"],
      past_activities: "Produced over 50 original tracks. DJ'd at school dances and local events. Released music on Spotify and SoundCloud. Collaborated with other artists online. Learning music theory and piano.",
      past_achievements: "Got 10,000 streams on Spotify. Paid gigs as DJ at 5 events. Won school talent show with original song. Featured on a music blog.",
      challenges: "I struggle with music theory and reading sheet music. I also find it hard to get consistent feedback on my tracks and grow my audience.",
      skills: {
        problemSolving: 3,
        communication: 3,
        technicalSkills: 4,
        creativity: 5,
        leadership: 2,
        selfManagement: 3,
      },
    },
  },
  {
    name: "Multilingual & Cultural Explorer",
    profile: {
      grade: 10,
      interests_free_text: "Learning languages, different cultures, travel, and international relations. Currently learning Spanish, Japanese, and Mandarin.",
      interests_by_category: {
        academic: true,
        creative: false,
        social: true,
        technical: false,
        sports: false,
        music: false,
        business: false,
        health_wellness: false,
        other: true,
      },
      goals_selected: ["college", "networking", "publicSpeaking"],
      goals_free_text: "I want to work in international relations, diplomacy, or become a translator. Living and working abroad is my dream.",
      time_availability_hours_per_week: 8,
      learning_preferences: ["reading", "video", "mentor"],
      past_activities: "Fluent in English and Spanish. Intermediate Japanese and beginner Mandarin. Pen pals with students from 5 different countries. Volunteer translator for community events. Host international exchange students.",
      past_achievements: "AP Spanish score of 5. Won Model UN best delegate award. Completed Japanese N3 certification. Published article in school's multicultural magazine.",
      challenges: "I spread myself too thin trying to learn multiple languages at once. I also struggle with speaking confidently in languages I'm still learning.",
      skills: {
        problemSolving: 3,
        communication: 4,
        technicalSkills: 2,
        creativity: 3,
        leadership: 3,
        selfManagement: 3,
      },
    },
  },
  {
    name: "Math & Competition Student",
    profile: {
      grade: 11,
      interests_free_text: "Mathematics, problem solving, mathematical olympiads, and theoretical physics. I love the elegance of mathematical proofs.",
      interests_by_category: {
        academic: true,
        creative: false,
        social: false,
        technical: true,
        sports: false,
        music: false,
        business: false,
        health_wellness: false,
        other: false,
      },
      goals_selected: ["stem", "college", "career"],
      goals_free_text: "I want to study pure mathematics or theoretical physics at a top university. Research in academia is my goal.",
      time_availability_hours_per_week: 15,
      learning_preferences: ["reading", "mentor", "handson"],
      past_activities: "Member of Math Olympiad team for 4 years. Self-studied calculus and linear algebra. Tutored peers in advanced math. Attended summer math programs at universities. Solved 500+ competition problems.",
      past_achievements: "AIME qualifier for 2 years. State Math League champion. Perfect score on AMC 12. Accepted to prestigious summer math camp.",
      challenges: "I sometimes get too absorbed in math and neglect other subjects. I also find group projects difficult because I prefer working alone.",
      skills: {
        problemSolving: 5,
        communication: 2,
        technicalSkills: 4,
        creativity: 4,
        leadership: 1,
        selfManagement: 4,
      },
    },
  },
  {
    name: "Social Justice Advocate",
    profile: {
      grade: 12,
      interests_free_text: "Social justice, civil rights, community organizing, and advocacy. I believe in using my voice to fight for equality.",
      interests_by_category: {
        academic: true,
        creative: false,
        social: true,
        technical: false,
        sports: false,
        music: false,
        business: false,
        health_wellness: false,
        other: true,
      },
      goals_selected: ["leadership", "publicSpeaking", "networking", "writing"],
      goals_free_text: "I want to become a civil rights lawyer or work for a nonprofit fighting for social justice. Law school is in my future.",
      time_availability_hours_per_week: 10,
      learning_preferences: ["reading", "group", "mentor"],
      past_activities: "Founded school's diversity and inclusion club. Organized voter registration drives. Spoke at city council meetings about youth issues. Interned at local ACLU chapter. Write opinion pieces for school newspaper.",
      past_achievements: "MLK Jr. service award recipient. Registered 100+ new voters. Published op-ed in local newspaper. Selected as youth representative for county equity committee.",
      challenges: "I sometimes get frustrated when progress is slow or when people disagree with me. I need to work on staying patient and finding common ground with others.",
      skills: {
        problemSolving: 4,
        communication: 5,
        technicalSkills: 1,
        creativity: 3,
        leadership: 5,
        selfManagement: 4,
      },
    },
  },
];
